# Generated by Django 6.0.3 on 2026-03-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
