# Generated by Django 6.0.3 on 2026-03-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
