# Generated by Django 6.0.3 on 2026-03-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_student_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='obtained_marks',
            field=models.IntegerField(default=0),
        ),
    ]
